export const DEFAULT_AVATAR = '/DefaultAvatar.png'
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const ADD_VOTE = 'ADD_VOTE'
export const ADD_QUESTION = 'ADD_QUESTION'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const ADD_VOTE_TO_USER = 'ADD_VOTE_TO_USER'
export const ADD_QUESTION_TO_USER = 'ADD_QUESTION_TO_USER'
